Story1/urls.py
from django.urls import path, include
from Story1.views import index

app_name = "Story1"

urlpatterns = [
   path('', index, name='Home'),
]

Story2/urls.py
from django.urls import path, include
from Story2.views import home, about, formSave, thanks, details

app_name = "Story2"

urlpatterns = [
   path('', home, name='Home'),
   path('about/', about, name='about'),
   path('forms/', formSave, name='forms'),
   path('thanks/', thanks, name='thanks'),
   path('details/<str:matkul_name>', details, name='details'),
]

Story7/urls.py
from django.urls import path, include
from .views import home, upload

app_name = "Story7"

urlpatterns = [
    path('', home, name='Home'),
    path('upload', upload, name="Upload"),
    # path('details/<str:objek>', details, name='Details'),
]

Story8/urls.py
from django.urls import path, include
from Story8.views import home, search, result

app_name = "Story8"

urlpatterns = [
    path('', home, name='Home'),
    path('search/', search, name="Search"),
    path('result/', result, name="Result"),
]

Story9/urls.py
from django.urls import path, include
from Story9.views import home, createUser

app_name = "Story9"

urlpatterns = [
    path('', home, name='Home'),
    path('sign_up/', createUser, name="SignUp")
]

landing_page/urls.py
from django.urls import path, include
from landing_page.views import landing_page

app_name = "landing_page"

urlpatterns = [
   path('', landing_page, name='Home'),
]

stories/urls.py
from django.contrib import admin
from django.urls import path, include
import Story2.urls, Story1.urls, landing_page.urls, Story7.urls, Story8.urls, Story9.urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(landing_page.urls)),
    path('Story1/', include(Story1.urls)),
    path('Story2/', include(Story2.urls)),
    path('Story7/', include(Story7.urls)),
    path('Story8/', include(Story8.urls)),
    path('Story9/', include(Story9.urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing_page/models.py
from django.db import models

# Create your models here.

landing_page/views.py
from django.shortcuts import render

def landing_page(request):
    return render(request,"landing_page.html")

landing_page/templates/include/navbar.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
    crossorigin="anonymous"
  />
  <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
  ></script>

  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap"
    rel="stylesheet"
  />
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark" style="background-color: rgb(255, 191, 53)">
      <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'landing_page:Home' %}" style="background-color: rgb(255, 191, 53)">Home</a>
      <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
      >
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href= "{% url 'Story1:Home' %}">Story1</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href= "{% url 'Story2:Home' %}">Story2</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href= "{% url 'Story7:Home' %}">Story7</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href= "{% url 'Story8:Home' %}">Story8</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href= "{% url 'Story9:Home' %}">Story9</a>
          </li>
          </ul>
      </div>
      </div>
    </nav>
  </body>
</html>