Story1/urls.py
from django.urls import path, include
from Story1.views import index

app_name = "Story1"

urlpatterns = [
   path('', index, name='Home'),
]

Story2/urls.py
from django.urls import path, include
from Story2.views import home, about, formSave, thanks, details

app_name = "Story2"

urlpatterns = [
   path('', home, name='Home'),
   path('about/', about, name='about'),
   path('forms/', formSave, name='forms'),
   path('thanks/', thanks, name='thanks'),
   path('details/<str:matkul_name>', details, name='details'),
]

Story7/urls.py
from django.urls import path, include
from .views import home, upload

app_name = "Story7"

urlpatterns = [
    path('', home, name='Home'),
    path('upload', upload, name="Upload"),
    # path('details/<str:objek>', details, name='Details'),
]

Story8/urls.py
from django.urls import path, include
from Story8.views import home, search, result

app_name = "Story8"

urlpatterns = [
    path('', home, name='Home'),
    path('search/', search, name="Search"),
    path('result/', result, name="Result"),
]

Story9/urls.py
from django.urls import path, include
from Story9.views import home, createUser

app_name = "Story9"

urlpatterns = [
    path('', home, name='Home'),
    path('sign_up/', createUser, name="SignUp")
]

landing_page/urls.py
from django.urls import path, include
from landing_page.views import landing_page

app_name = "landing_page"

urlpatterns = [
   path('', landing_page, name='Home'),
]

stories/urls.py
from django.contrib import admin
from django.urls import path, include
import Story2.urls, Story1.urls, landing_page.urls, Story7.urls, Story8.urls, Story9.urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(landing_page.urls)),
    path('Story1/', include(Story1.urls)),
    path('Story2/', include(Story2.urls)),
    path('Story7/', include(Story7.urls)),
    path('Story8/', include(Story8.urls)),
    path('Story9/', include(Story9.urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing_page/models.py
from django.db import models

# Create your models here.

landing_page/views.py
from django.shortcuts import render

def landing_page(request):
    return render(request,"landing_page.html")

landing_page/templates/about.html
{% extends "templateStory2.html" %}
    {% block title %} Story2-About {% endblock%}
    {% block content%}
    <div class="textboxtitle">
        Salam dari Developer
    </div>
    <div class = "container" style ="margin-left: 250px; margin-right: 200px; margin-top: 25px;">
        <div class="textbox" >
            <p style="font-size: 25px;">Halo, nama saya Mikhael Deo Barli</p>
            <p> Sekarang saya sedang mengemban ilmu dalam bidang Ilmu Komputer</p>
            <img src="/static/CV.JPG" class="img-responsive" style="display: block; margin-left: auto; margin-right: auto; width: 50%;">
        </div>
    </div>
    {% endblock %}

landing_page/templates/base_story7.html
{% extends "base_template.html" %}

  {% block body %}

  <!-- JQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src = "https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>

  <div id="sidebar" class="sidebar">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a href="{% url 'Story7:Home' %}">Story 7</a>
      <a href="{% url 'Story7:Upload'%}">Upload Something</a>
  </div>
  
  <div id="main">
    <button class="openbtn" onclick="openNav()">&#9776;Sidebar</button>
    <div class="container" style="margin-top: 20px;">
      {% block content %}
      {% endblock %}
    </div>
  </div>

  <script src="/static/js/sidebar.js"></script>
  {% endblock %}

landing_page/templates/base_story8.html
{% extends "base_template.html" %}

  {% block body %}

  <!-- JQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src = "https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>

  <div id="sidebar" class="sidebar">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a href="{% url 'Story8:Home' %}">Story 8</a>
      <a href="{% url 'Story8:Search' %}">Find Something</a>
  </div>
  
  <div id="main">
    <button class="openbtn" onclick="openNav()">&#9776;Sidebar</button>
    <div class="container" style="margin-top: 20px;">
      {% block content %}
      {% endblock %}
    </div>
  </div>

  <script src="/static/js/sidebar.js"></script>
  {% endblock %}

landing_page/templates/base_story9.html
{% extends "base_template.html" %}

  {% block body %}

  <!-- JQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src = "https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>

  <div id="sidebar" class="sidebar">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a href="{% url 'Story9:Home' %}">Story 9</a>
      {% if user.is_authenticated %}
      <a href="{% url 'logout' %}">Logout</a>
      {% else %}
      <a href="{% url 'login' %}">Login</a>
      {% endif %}
      {% if user.is_authenticated %}
      <div style="bottom: 40px;">
        Hallo, {{user.name}} !
      </div>
      {% endif %}
  </div>
  
  <div id="main">
    <button class="openbtn" onclick="openNav()">&#9776;Sidebar</button>
    <div class="container" style="margin-top: 20px;">
      {% block content %}
      {% endblock %}
    </div>
  </div>

  <script src="/static/js/sidebar.js"></script>
  {% endblock %}

landing_page/templates/create_user9.html
{% extends "base_story9.html" %} 
    {% load crispy_forms_tags %}     

    {% block content %}
    <form method="POST" action="{% url 'Story9:SignUp' %}">
        {% csrf_token %}
        {{UserForm|crispy}}
        {{PhotoForm|crispy}}
        <br>
        <button class="button" type="submit">Sign Up</button>
    </form>
    {% endblock %}

landing_page/templates/detailMatkul.html
{% extends "templateStory2.html" %}
    {% block title %} {{MatKul.name}} {% endblock%}
    {% block content%}
    <div class="textboxtitle">
        {{MatKul.name}}
    </div>

    <div class = "container" style ="margin-left: 250px; margin-right: 200px; margin-top: 25px;">
        <div class="textbox">
            <p>SKS         :{{MatKul.sks}}</p>
            <p>IP          :{{MatKul.ip}}</p>
            <p>Dosen       :{{MatKul.dosen}}}</p>
            <p>Kelas       :{{MatKul.kelas}}</p>
            <p>Semester    :{{MatKul.semester}}</p>
            <p>Deskripsi   :{{MatKul.desc}}</p>
        </div>
    </div>
    {% endblock %}

landing_page/templates/forms.html
{% extends "templateStory2.html" %}
    {% block title %} Story2-Forms {% endblock%}
    {% block content%}
    <div class="textboxtitle">
        Story2-Forms
    </div>
    <div class="textbox" style="margin-top: 125px; margin-left: 250px; margin-right: 250px;">
        <form action="{% url 'Story2:home' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
      </form>
    </div>
    
    {% endblock %}

landing_page/templates/home.html
{% extends "templateStory2.html" %}
    {% block title %} Story2-Home {% endblock%}
    {% block content%}
    <div class="textboxtitle">
        Story2-Home
    </div>
  
    <div class="container-fluid" style="margin-top: 50px; margin-left: 250px; margin-right: 250px;"> 
        <div class="textbox">
            <table class="table table-borderless">
                {% for MatKul in MatKuls %}
                <tr>
                    <td>Mata Kuliah      :<a href = "{% url 'Story2:details' MatKul.name %}">{{MatKul.name}}</a></td>
                </tr>    
                {% endfor %}
            </table>
        </div>
    </div>
   

    {% endblock %}

landing_page/templates/index.html
{% extends "base_template.html" %}

landing_page/templates/landing_page.html
{% extends "base_template.html "%}

landing_page/templates/search_story8.html
{% extends "base_story8.html" %}
    {% load crispy_forms_tags %}

    {% block content %}
    <script src="/static/js/search.js"></script>
    <form action="{% url 'Story8:Result'%}" method="GET" enctype="multipart/form-data" id="search-form">
        {{form|crispy}}
    </form>
    <table class="table" id="search_result">
        <thead>
          <tr>
            <th scope="col">Nama Buku</th>
            <th scope="col">Sampul Buku</th>
          </tr>
        </thead>
        <tbody>
            <!-- Data will be here -->
        </tbody>
    </table>
    {% endblock %}

landing_page/templates/templateStory2.html
{% extends "base_template.html" %}
    {% block content %}
    {% endblock %}

landing_page/templates/thanks.html
{% extends "templateStory2.html" %}
    {% block title %} Story2-THANKS! {% endblock%}
    {% block content%}
    <div class="textboxtitle">
        Thank you for your participation
    </div>
    {% endblock %}

landing_page/templates/upload7.html
{% extends "base_story7.html" %}
    {% load crispy_forms_tags %}

    {% block content %}
    <div>
        <form action="{% url 'Story7:Upload' %}" method="POST" enctype="multipart/form-data"> 
            {% csrf_token %}
            <div>
                {{userForm|crispy}}
            </div> 
            <br>
            {{ aktivitasForm.management_form }}
            {% for aktivitas in aktivitasForm %}
                <div>
                    {{aktivitas|crispy}}
                </div>
            <br>
            {% endfor %}
            {{ organisasiForm.management_form }}
            {% for organisasi in organisasiForm %}
            <div>
                <div>{{organisasi.name|as_crispy_field}}</div>
                <div class="input-group date" id="datetimepicker_organisasi_dateStart" data-target-input="nearest">
                    {{organisasi.dateStart|as_crispy_field}}
                    <div class="input-group-append" data-target="#datetimepicker_organisasi_dateStart" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                </div>
                <div class="input-group date" id="datetimepicker_organisasi_dateEnd" data-target-input="nearest">
                    {{organisasi.dateEnd|as_crispy_field}}
                    <div class="input-group-append" data-target="#datetimepicker_organisasi_dateEnd" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                </div>
            </div>
            <br>
            {% endfor %}
            {{ prestasiForm.management_form }}
            {% for prestasi in prestasiForm %}
            <div>
                <div>{{prestasi.name|as_crispy_field}}</div>
                <div class="input-group date" id="datetimepicker_prestasi_dateAcquired" data-target-input="nearest">
                    {{prestasi.dateAcquired|as_crispy_field}}
                    <div class="input-group-append" data-target="#datetimepicker_prestasi_dateAcquired" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                </div>
            </div>
            <br>
            {% endfor %}
            <button class="button" type="submit">Upload</button>
        </form>
    </div>
    {% endblock %}